name: Kwakmanbo Community CI
on:
  push:
    branches:
      # main 브랜치에서 push가 발생하면
      - main
  pull_request:
    branches:
      # main 브랜치에 PR이 발생하면
      - main

jobs:
  fe-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 19.x,20.x,22.x,24.x ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Node Enviornment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build-and-push-image-to-ecr:
    needs: fe-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build, tag and push image to Aamazon ECR Public Registry
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: community/fe
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG





