name: Kwakmanbo Community CI
on:
  push:
    branches:
      # main 브랜치에서 push가 발생하면
      - main
  pull_request:
    branches:
      # main 브랜치에 PR이 발생하면
      - main

jobs:
  fe-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          node-version: [ 24.x ]
#        node-version: [ 19.x,20.x,22.x,24.x ]

    steps:
      - uses: actions/checkout@v5


      - name: Set up Node Enviornment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build-and-push-image-to-ecr:
    needs: fe-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'


    steps:
#      - name: Get fe Enviorment
#        uses: actions/checkout@v5
#
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
#
#
#      - name: Login to Amazon ECR
#        id: login-ecr
#        uses: aws-actions/amazon-ecr-login@v2
#        with:
#          registry-type: public
#
#      - name: Build, tag and push image to Aamazon ECR Public Registry
#        id: build-image
#        env:
#          REGISTRY: public.ecr.aws/${{ secrets.AWS_REPOSITORY_ALIAS }}
#          REPOSITORY: ${{ secrets.AWS_REPOSITORY }}
#          IMAGE_TAG: ${{ github.sha }}
#        run: |
#          pwd
#          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
#          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Install AWS CLI if not installed
        run: |
          if ! command -v aws &> /dev/null
          then
            echo "AWS CLI not found. Installing..."
            sudo apt-get update
            sudo apt-get install -y awscli
          else
            echo "AWS CLI already installed."
          fi

      - name: Deploy FE EC2 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --instance-ids ${{ secrets.AWS_INSTANCE_ID }} \
            --parameters commands='["cd /home","mkdir hello_world"]'