name: Kwakmanbo Community CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fe-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 19.x,20.x,22.x,24.x ]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Node Enviornment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build-and-push-image-to-ecr:
    needs: fe-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Get fe Enviorment
        uses: actions/checkout@v5

      - name: Configure AWS Credentials For build
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build, tag and push image to Aamazon ECR Public Registry
        id: build-image
        env:
          REGISTRY: public.ecr.aws/${{ secrets.AWS_REPOSITORY_ALIAS }}
          REPOSITORY: ${{ secrets.AWS_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            bash /home/ubuntu/deploy.sh ${{ secrets.AWS_REPOSITORY_ALIAS }} ${{ secrets.AWS_REPOSITORY }} latest